export const qualityWords: string[] = [
  'ultra-realistic',
  'photorealistic details',
  'volumetric lighting',
  'sharp focus',
  'depth of field',
  'bokeh',
  'masterpiece',
  'hyperdetailed',
  'censored',
  'blurry',
  'disfigured',
  'bad anatomy',
  'blurry background',
  'grainy',
  'noise',
  'dynamic angle',
  'rule of thirds',
  'golden ratio',
  'cinematic lighting',
  'studio lighting',
  'rim lighting',
  'volumetric light',
  'god rays',
  'trending on artstation',
  'artstation HQ',
  'film grain',
  'chromatic aberration',
  'anamorphic bokeh',
  'depth blur',
  'sharpen',
  'detailed',
  'intricate',
  'fine details',
  'texture',
  'skin pores',
  'sweat',
  'silk',
  'pale skin',
  'dark skin',
  'asian skin',
  'caucasian skin',
  'black skin',
  'hispanic skin',
  'indian skin',
  'mixed race skin',
  'alien skin',
  'monster skin',
  'robot skin',
  'android skin',
  'cyborg skin',
  'zombie skin',
  'vampire skin',
  'werewolf skin',
  'demon skin',
  'angel skin',
  'fairy skin',
  'elf skin',
  'dwarf skin',
  'orc skin',
  'goblin skin',
  'mermaid skin',
  'siren skin',
  'harpy skin',
  'centaur skin',
  'minotaur skin',
  'satyr skin',
  'faun skin',
  'gorgon skin',
  'medusa skin',
  'succubus skin',
  'incubus skin',
  'oni skin',
  'kitsune skin',
  'tanuki skin',
  'kappa skin',
  'tengu skin',
  'yokai skin',
  'ghost skin',
  'spirit skin',
  'phantom skin',
  'wraith skin',
  'specter skin',
  'ghoul skin',
  'lich skin',
  'golem skin',
  'elemental skin',
  'shadow skin',
  'light skin',
  'cosmic skin',
  'celestial skin',
  'abyssal skin',
  'infernal skin',
  'ethereal skin',
  'spectral skin',
  'astral skin',
  'dream skin',
  'nightmare skin',
  'fantasy skin',
  'sci-fi skin',
  'cyberpunk skin',
  'steampunk skin',
  'dieselpunk skin',
  'atompunk skin',
  'solarpunk skin',
  'biopunk skin',
  'nanopunk skin',
  'mythological skin',
  'folklore skin',
  'legendary skin',
  'mythical skin',
  'epic skin',
  'heroic skin',
  'villainous skin',
  'anti-hero skin',
  'magical skin',
  'cursed skin',
  'blessed skin',
  'sacred skin',
  'profane skin',
  'divine skin',
  'demonic skin',
  'holy skin',
  'unholy skin',
  'corrupted skin',
  'pure skin',
  'innocent skin',
  'guilty skin',
  'ashamed skin',
  'proud skin',
  'happy skin',
  'sad skin',
  'angry skin',
  'scared skin',
  'surprised skin',
  'disgusted skin',
  'bored skin',
  'excited skin',
  'confused skin',
  'curious skin',
  'thoughtful skin',
  'pensive skin',
  'dreamy skin',
  'sleepy skin',
  'awake skin',
  'alert skin',
  'focused skin',
  'distracted skin',
  'calm skin',
  'nervous skin',
  'relaxed skin',
  'tense skin',
  'strong skin',
  'weak skin',
  'healthy skin',
  'sick skin',
  'injured skin',
  'healing skin',
  'dying skin',
  'dead skin',
  'living skin',
  'breathing skin',
  'pulsating skin',
  'vibrating skin',
  'glowing skin',
  'shining skin',
  'sparkling skin',
  'flickering skin',
  'blinking skin',
  'changing skin',
  'transforming skin',
  'morphing skin',
  'evolving skin',
  'mutating skin',
  'growing skin',
  'shrinking skin',
  'expanding skin',
  'contracting skin',
  'melting skin',
  'freezing skin',
  'burning skin',
  'smoking skin',
  'steaming skin',
  'bubbling skin',
  'dripping skin',
  'oozing skin',
  'bleeding skin',
  'sweating skin',
  'crying skin',
  'laughing skin',
  'smiling skin',
  'frowning skin',
  'grinning skin',
  'pouting skin',
  'smirking skin',
  'winking skin',
  'blushing skin',
  'palms sweating',
  'goosebumps',
  'shivering',
  'trembling',
  'quivering',
  'pulsing',
  'throbbing',
  'flushing',
  'pale',
  'flushed',
  'rosy',
  'tan',
  'sun-kissed',
  'bronzed',
  'golden',
  'silvery',
  'glowing',
  'radiant',
  'luminous',
  'translucent',
  'transparent',
  'opalescent',
  'iridescent',
  'shimmering',
  'sparkling',
  'glittering',
  'glistening',
  'wet',
  'moist',
  'damp',
  'sweaty',
  'oily',
  'greasy',
  'smooth',
  'silky',
  'velvety',
  'rough',
  'bumpy',
  'scaly',
  'spiky',
  'hairy',
  'furry',
  'feathered',
  'scaled',
  'plated',
  'armored',
  'metallic',
  'rocky',
  'stony',
  'wooden',
  'earthen',
  'fiery',
  'watery',
  'airy',
  'ethereal',
  'smoky',
  'misty',
  'cloudy',
  'clear',
  'pure',
  'clean',
  'dirty',
  'grimy',
  'stained',
  'spotted',
  'blotchy',
  'streaky',
  'streaked',
  'patterned',
  'textured',
  'grained',
  'marbled',
  'veined',
  'lined',
  'striped',
  'checkered',
  'polka-dotted',
  'floral',
  'geometric',
  'abstract',
  'swirling',
  'spiraling',
  'wavy',
  'curved',
  'straight',
  'angular',
  'sharp',
  'blunt',
  'smooth',
  'rough',
  'soft',
  'hard',
  'light',
  'dark',
  'bright',
  'dim',
  'vibrant',
  'dull',
  'muted',
  'pastel',
  'neon',
  'monochromatic',
  'colorful',
  'rainbow',
  'golden hour',
  'blue hour',
  'twilight',
  'dawn',
  'dusk',
  'day',
  'night',
  'sunlight',
  'moonlight',
  'starlight',
  'city lights',
  'streetlights',
  'headlights',
  'taillights',
  'traffic lights',
  'neon signs',
  'storefronts',
  'windows',
  'reflections',
  'shadows',
  'silhouettes',
  'highlights',
  'lowlights',
  'midtone',
  'contrast',
  'exposure',
  'white balance',
  'color temperature',
  'hue',
  'saturation',
  'luminance',
  'vibrance',
  'sharpness',
  'clarity',
  'detail',
  'texture',
  'grain',
  'noise',
  'vignette',
  'chromatic aberration',
  'lens flare',
  'bokeh',
  'depth of field',
  'shallow depth of field',
  'deep depth of field',
  'tilt-shift',
  'macro',
  'wide angle',
  'fisheye',
  'telephoto',
  'zoom',
  'prime lens',
  'aperture',
  'shutter speed',
  'ISO',
  'white balance',
  'metering mode',
  'exposure compensation',
  'flash',
  'fill light',
  'backlight',
  'rim light',
  'key light',
  'fill light',
  'hair light',
  'kicker light',
  'practical light',
  'ambient light',
  'natural light',
  'artificial light',
  'soft light',
  'hard light',
  'diffused light',
  'specular highlight',
  'specular reflection',
  'diffuse reflection',
  'subsurface scattering',
  'global illumination',
  'ambient occlusion',
  'screen space ambient occlusion',
  'ray tracing',
  'path tracing',
  'radiosity',
  'photometric light',
  'volumetric light',
  'god rays',
  'light shafts',
  'crepuscular rays',
  'light bloom',
  'lens dirt',
  'dust particles',
  'smoke',
  'fog',
  'haze',
  'mist',
  'clouds',
  'sky',
  'sun',
  'moon',
  'stars',
  'planets',
  'galaxy',
  'universe',
  'space',
  'cosmos',
  'nebula',
  'black hole',
  'wormhole',
  'supernova',
  'meteor',
  'asteroid',
  'comet',
  'satellite',
  'spaceship',
  'alien',
  'ufo',
  'extraterrestrial',
  'monster',
  'creature',
  'beast',
  'demon',
  'devil',
  'angel',
  'god',
  'goddess',
  'myth',
  'legend',
  'folklore',
  'fairytale',
  'storybook',
  'dream',
  'nightmare',
  'fantasy',
  'sci-fi',
  'cyberpunk',
  'steampunk',
  'post-apocalyptic',
  'dystopian',
  'utopian',
  'historical',
  'futuristic',
  'modern',
  'vintage',
  'retro',
  'abstract',
  'surreal',
  'minimalist',
  'maximalist',
  'realistic',
  'stylized',
  'cartoon',
  'anime',
  'manga',
  'comic',
  'graphic novel',
  'illustration',
  'painting',
  'drawing',
  'sketch',
  'sculpture',
  'statue',
  'bust',
  'relief',
  'mural',
  'graffiti',
  'street art',
  'fine art',
  'modern art',
  'classical art',
  'renaissance art',
  'baroque art',
  'rococo art',
  'neoclassical art',
  'romanticism art',
  'realism art',
  'impressionism art',
  'post-impressionism art',
  'expressionism art',
  'cubism art',
  'futurism art',
  'surrealism art',
  'abstract expressionism art',
  'pop art',
  'op art',
  'minimal art',
  'conceptual art',
  'performance art',
  'installation art',
  'land art',
  'body art',
  'digital art',
  'new media art',
  'generative art',
  'algorithmic art',
  'ai art',
  'machine learning art',
  'neural network art',
  'deep learning art',
  'style transfer',
  'diffusion model',
  'stable diffusion',
  'midjourney', 'dall-e',
  'runwayml', 'artbreeder', 'deepart', 'neural style transfer', 'gan', 'vae', 'diffusion', 'transformer',
  'attention', 'latent space', 'embedding', 'vector', 'tensor', 'matrix', 'array', 'data', 'algorithm',
  'code', 'script', 'program',
  'software', 'hardware', 'computer', 'server', 'network', 'internet',
  'web', 'cloud', 'blockchain', 'cryptocurrency', 'nft', 'metaverse', 'virtual reality', 'augmented reality',
  'mixed reality', 'extended reality', 'artificial intelligence', 'machine intelligence',
  'cognitive computing', 'robotics', 'automation', 'sim', 'simulation', 'model', 'prototype',
  'design', 'architecture', 'engineering', 'science', 'technology', 'innovation', 'creativity',
  'imagination', 'vision', 'dream', 'fantasy', 'reality', 'truth', 'lie', 'deception', 'illusion',
  'magic', 'mystery', 'secret', 'puzzle', 'riddle', 'enigma', 'paradox', 'conundrum', 'dilemma',
  'choice', 'decision', 'fate', 'destiny', 'chance', 'luck', 'fortune', 'misfortune', 'happiness',
  'sadness',
  'joy',
  'sorrow',
  'love',
  'hate',
  'peace',
  'war',
  'life',
  'death',
  'beginning',
  'end',
  'past',
  'present',
  'future',
  'time',
  'space',
  'dimension',
  'universe',
  'multiverse',
  'omniverse',
  'metaverse',
  'alterverse',
  'hyperverse',
  'parallel universe',
  'alternate reality',
  'dream world',
  'spirit world',
  'underworld',
  'heaven',
  'hell',
  'purgatory',
  'limbo',
  'nirvana',
  'paradise',
  'eden',
  'utopia',
  'dystopia',
  'apocalypse',
  'post-apocalypse',
  'cataclysm',
  'doomsday',
  'armageddon',
  'rapture',
  'renaissance',
  'revolution',
  'evolution',
  'creation',
  'destruction',
  'chaos',
  'order',
  'balance',
  'harmony',
  'discord',
  'conflict',
  'struggle',
  'fight',
  'battle',
  'warfare',
  'combat',
  'duel',
  'skirmish',
  'clash',
  'encounter',
  'confrontation',
  'showdown',
  'contest',
  'competition',
  'race',
  'challenge',
  'quest',
  'journey',
  'adventure',
  'expedition',
  'exploration',
  'discovery',
  'revelation',
  'enlightenment',
  'awakening',
  'ascension',
  'descent',
  'fall',
  'rise',
  'growth',
  'decay',
  'birth',
  'rebirth',
  'renewal',
  'regeneration',
  'transformation',
  'metamorphosis',
  'change',
  'stasis',
  'motion',
  'stillness',
  'silence',
  'sound',
  'music',
  'noise',
  'melody',
  'rhythm',
  'harmony',
  'cacophony',
  'symphony',
  'orchestra',
  'choir',
  'solo',
  'duet',
  'trio',
  'quartet',
  'quintet',
  'ensemble',
  'band',
  'group',
  'crowd',
  'audience',
  'spectator',
  'viewer',
  'listener',
  'reader',
  'writer',
  'artist',
  'creator',
  'maker',
  'builder',
  'destroyer',
  'preserver',
  'guardian',
  'protector',
  'savior',
  'hero',
  'heroine',
  'villain',
  'anti-hero'
];
